### ISSUE TITLE
Hooking non-fatal signals

### ISSUE THREAD

**Issue by iarna** [bcoe/signal-exit#1]
You seem to be hooking the entire signal list here, but a bunch of these aren't actually fatal so the program will just continue to run.

For example,

SIGWINCH will be called any time you resize your terminal window

SIGUSR1 triggers the debugger and is non-fatal.

SIGCHLD will be called any time a spawned process dies.

SIGSTOP is used to suspend the program (and I don't think can be trapped)
SIGCONT is used to resume a program

Experimentation shows that:

SIGIO – is non-fatal on MacOS and fatal on Linux
SIGURG – is non-fatal on both

Also:

SIGTSTP, SIGTTIN, SIGTTOU seem to suspend too but I'm not familiar with them so I don't know when they'd be called organically.

And of course SIGKILL is untrappable.

**Comment by bcoe** [comment]
@iarna thanks for testing this, I'll amend this list of signals. CC: @isaacs.

**Comment by bcoe** [comment]
Could we get away with a much smaller list of handled signals, e.g.,

http://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html
